### ISSUE TITLE
Understanding Read from Datastore and query splits, and other behaviour of dataflow

### ISSUE THREAD

**Issue by 1byxero** [GoogleCloudPlatform/DataflowPythonSDK#45] opened 2017-08-30 07:29 UTC
I am running a dataflow pipeline which reads huge data from datastore, maps each entity to bigquery TableRow and writing it.

To understand the complete flow of the jobs i introduced an error in step of mapping each entity to bigqquery tablerow. Error is if entity has a X value for a Y attribute then raise ValueError

There is only one entry in datastore which causes this error, but in the dataflow runner console i see the error more than once, to be precise i ran the job twice. for first job the valueerror was raised 4 times and for second time the valueerror was raised 7 times.

I am unable to understand since there is one entity which should cause this error
then why is it caused more than once?

Also the job fails due to following issue
```
 A work item was attempted 4 times without success. Each time the worker eventually lost contact with the service. The work item was attempted on: 
<job_name>-1-08292326-f3a3-harness-zmmq,
<job_name>-1-08292326-f3a3-harness-z0bt,
<job_name>-1-08292326-f3a3-harness-zmmq,
<job_name>-1-08292326-f3a3-harness-k9bk
```

I searched and found out that it might be caused due to memory limitations, but i ran the same job before without introducing the error and the autoscaling handled it properly.

Why is this behaviour caused, what am i missing?

P.S. @aaltay  Sorry to open up so many issue, I am trying to understand and learn DataFlow and since the community is not that big, i have to come here to ask questions.

**Comment by 1byxero** [comment] 2017-08-30 08:47
[This SO answer](https://stackoverflow.com/questions/41215541/dataflow-jobs-fail-after-a-few-410-errors-while-writing-to-gcs/41228810#41228810)
Mentions that `Dataflow will fail the job if a single bundle fails 4 times.`
What does that mean exactly?

Also after reading that i tried to Raise errors only once, and to my surprise the job Completed successfully.
P.S. the error was raised twice. Still dont understand why this happened.

**Comment by 1byxero** [comment] 2017-08-30 09:16
So after reading [this link](https://cloud.google.com/dataflow/pipelines/troubleshooting-your-pipeline) I found out that, dataflow tries to retry a task 4 times if it fails.
So I can understand that the ValueError can be raised 4 times.
But as i mentioned before, in the second try the ValueError was raised 7 times.

Is it that the query spilt might have common values?

**Comment by aaltay** [comment] 2017-08-30 17:13
Query split should not have common values (that will result in duplicate data), unless there is a bug. If there is only 1 item with an issue then 4 errors make sense (due to retries).

7 errors is confusing to me. How do you reproduce this?

(cc: @vikkyrk, @cph6 to confirm that query split does not cause duplicate items.)

(In general, the best place to ask questions are SO. Because it is easier for other developers to discover those questions.)

**Comment by 1byxero** [comment] 2017-08-30 19:48
So to explain what I am doing, so you might me able to recreate the issue.
I am reading all records of specific kind from data store, converting them into BigQuery tablerow and then writing to big query

The pipeline has 3 steps
1. ReadFromDataStore - this is the library function provided by beam
2. Convert to tableRow - Beam.Map function to convert the entities to BigQuery TableRow
3. Write to Bigquery - Uses beam library function to write to bigquery

Now there is one specific entity in the datastore X with value of Attribute Foo = fooBar.
Now if I encountere this entity in step 2 of pipeline i.e. Convert to tableRow, then I raise a ValueError

You might be able to recreate it using above steps

My intention of doing this was just to see if in cases which might raise some errors, will the PCollection item which didn't cause the errors will be written to BigQuery or not.

To give more info,
The Data store kind has about 1600000.
Out of which the kind which has that specific attribute Foo with value fooBar is only one, so that Value error will occur at most 4 times due to retries.

**Comment by 1byxero** [comment] 2017-09-11 11:34
As [this link](https://cloud.google.com/dataflow/service/dataflow-service-desc#error-and-exception-handling) suggests

```Note: When processing in batch mode, you might see a large number of individual failures before a pipeline job fails completely (which happens when any given bundle fails after four retry attempts). For example, if your pipeline attempts to process 100 bundles, Dataflow could theoretically generate several hundred individual failures until a single bundle reaches the 4-failure condition for exit.```

So, for the issue that raised more than 4 errors, is it possible to get same data in multiple bundles?
Might be a bug?

**Comment by aaltay** [comment] 2017-10-03 18:01
It should be fine to re-read same data after a failed retry however this process should not generate duplicates. Unless there is a bug as you mentioned.

**Comment by CristianTurcios** [comment] 2018-05-02 05:05
Hello @1byxero , you could share your project in github to be able to guide me from it, as you mention even the dataflow community is not very big and I am looking to explore it and do exactly what you mention that you already did

ReadFromDataStore
Convert to tableRow
Write to Bigquery

thank you very much

**Comment by 1byxero** [comment] 2018-05-02 06:10
Hi @CristianTurcios , The project i used above things is not owned by me, hence i wouldnt be able to share it on github.
The SDK provides `ReadFromDatastore` method which will help you to extract data from google datastore. Then you can use [`googledatastore`](https://readthedocs.org/projects/googledatastore/) to read and manipulate datastore entities. Using those you need to just create python dicts to create bigquery table rows to insert in BQ using the sink provided in beam SDK.

**Comment by meredithslota** [comment] 2022-06-29 16:10
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.

**Closed as completed by meredithslota** 2022-06-29 16:10 UTC
